#!/usr/bin/env bash

_main_dir=$(dirname $BASH_SOURCE)
EASYPAPDIR=${EASYPAPDIR:-${_main_dir}}
. ${_main_dir}/script/easypap-common.bash
unset _main_dir

error()
{
    echo "$@" >&2
    exec ${VIEW} -h
}

COMPARE=no
TRACEFILE=no
ARGS=()

for ((i = 1; i <= $#; i++ )); do
    case ${!i} in
        -c|--compare)
            COMPARE=yes
            continue
            ;;
        -d|--dir)
            if (( i + 1 > $#)); then
                error "Missing trace directory"
            fi
            n=$((i + 1))
            TRACEDIR=${!n}
            ARGS+=("${!i}")
            i=$((i + 1))
            ;;
        -p|--params)
            # use params file if available
            use_params=yes
            continue
            ;;
        -i|--iteration)
            if ((i + 1 > $#)); then
                error "Missing iteration number"
            fi
            ARGS+=("${!i}")
            i=$((i + 1))
            ;;
        -r|--range)
            if ((i + 2 > $#)); then
                error "Missing range parameter"
            fi
            ARGS+=("${!i}")
            i=$((i + 1))
            ARGS+=("${!i}")
            i=$((i + 1))
            ;;
        -b|--brightness)
            if ((i + 1 > $#)); then
                error "Missing brightness parameter"
            fi
            ARGS+=("${!i}")
            i=$((i + 1))
            ;;
        -a|--align)
            ;;
        -w|--whole-trace)
            ;;
        -h|--help)
            ;;
        *)
            TRACEFILE=yes
            ;;
    esac
    ARGS+=("${!i}")
done

if [[ ${use_params} = yes ]]; then
    if [[ -f ${TRACEDIR}/params.txt ]]; then
        ARGS+=($(cat ${TRACEDIR}/params.txt))
        exec $0 ${ARGS[@]}
    else
        echo "Warning: Params not found"
    fi

fi

# build easyview if needed
if [[ ! -f ${VIEW} ]]; then
    echo "Building ${VIEW}"
    make -C ${EASYPAPDIR}/traces
fi

if [[ ${COMPARE} == "yes" ]]; then
    [[ -f ${TRACEDIR}/${CUR_TRACEFILE} && -f ${TRACEDIR}/${PREV_TRACEFILE} ]] || error "Comparing trace files requires two files under ${TRACEDIR}"
    ARGS+=("${TRACEDIR}/${CUR_TRACEFILE}" "${TRACEDIR}/${PREV_TRACEFILE}")
    TRACEFILE=yes
fi

if [[ ${TRACEFILE} == "no" ]]; then
    [[ -f ${TRACEDIR}/${CUR_TRACEFILE} ]] || error "Trace file not found under ${TRACEDIR}"
    ARGS+=("${TRACEDIR}/${CUR_TRACEFILE}")
fi

#echo "exec ${VIEW} ${ARGS[@]}"
exec ${VIEW} ${ARGS[@]}
