#!/usr/bin/env bash

_script_dir=$(dirname $BASH_SOURCE)
EASYPAPDIR=${EASYPAPDIR:-$(realpath ${_script_dir}/..)}
. ${_script_dir}/easypap-common.bash
unset _script_dir

usage()
{
    echo "Usage: $PROGNAME [ option ]"
    echo "option can be:" 
    echo "  -h | --help: display help"
    echo "  -c | --clean: clean before building"

    exit $1
}

PROGNAME=$0

cleaning=0

while [[ $# -ge 1 ]]; do
    case $1 in
        -h|--help)
            usage 0
            ;;
        -c|--clean)
            cleaning=1
            ;;
        *)
            break
            ;;
    esac
    shift
done

if [[ $cleaning = 1 ]]; then
    for dir in lib/ezv lib/ezm lib/ezm/view . ; do
        make -C $dir clean || exit 1
    done
else
    for dir in lib/ezv lib/ezm lib/ezm/view . ; do
        make -C $dir -j || exit 1
    done
fi

exit 0
