#!/usr/bin/env bash

_script_dir=$(dirname $BASH_SOURCE)
EASYPAPDIR=${EASYPAPDIR:-$(realpath ${_script_dir}/..)}
. ${_script_dir}/easypap-utilities.bash
unset _script_dir

if [ $# != 1 ]; then
    echo "Usage: easypap-list-variants <kernel>"
    exit 1
fi

_easypap_variants "$1"

if [ ! -z "$variants" ]; then
    echo $variants
fi

exit 0
