
#ifndef CONSTANTS_IS_DEF
#define CONSTANTS_IS_DEF

#define DEFAULT_DIM 1024
#define DEFAULT_CPU_TILE_SIZE 32
#define DEFAULT_GPU_TILE_SIZE 16

#define DEFAULT_KERNEL "none"
#define DEFAULT_VARIANT "seq"
#define DEFAULT_OCL_VARIANT "ocl"

#endif
